<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE blueColumn [
  <!ELEMENT blueColumn (column,NeuronTypes,Seeds?,SynapsesProperties,SynapsesClassification,DendriticMorphologyProbabilities,TouchRules,InterBoutonInterval?)>
  <!ELEMENT column (layer*)>
  <!ATTLIST column id CDATA #REQUIRED x CDATA #REQUIRED z CDATA #REQUIRED>
  <!ELEMENT layer (#PCDATA)>
  <!ATTLIST layer	id CDATA #REQUIRED height CDATA #REQUIRED>
  <!ELEMENT NeuronTypes (Layer*)>
  <!ATTLIST NeuronTypes totalNeurons CDATA #REQUIRED miniColumns CDATA #REQUIRED IntExtendedMinicolumnRadious CDATA #REQUIRED>
  <!ELEMENT Layer (StructuralType*)>
  <!ATTLIST Layer id CDATA #REQUIRED percentage CDATA #REQUIRED>
  <!ELEMENT StructuralType (ElectroType*)>
  <!ATTLIST StructuralType id CDATA #REQUIRED percentage CDATA #REQUIRED sigma CDATA #REQUIRED exclusionRadius CDATA #REQUIRED mClass CDATA #REQUIRED sClass CDATA #REQUIRED spineLength CDATA #REQUIRED>
  <!ELEMENT ElectroType (#PCDATA)>
  <!ATTLIST ElectroType id CDATA #REQUIRED percentage CDATA #REQUIRED>
  <!ELEMENT Seeds (#PCDATA)>
  <!ATTLIST Seeds recipeSeed CDATA #IMPLIED columnSeed CDATA #IMPLIED synapseSeed CDATA #IMPLIED>
  <!ELEMENT InterBoutonInterval (#PCDATA)>
  <!ATTLIST InterBoutonInterval minDistance CDATA #IMPLIED maxDistance CDATA #IMPLIED regionGap CDATA #IMPLIED>
  <!ELEMENT SynapsesProperties (synapse*)>
  <!ELEMENT synapse (#PCDATA)>
  <!ATTLIST synapse id1 CDATA #REQUIRED id2 CDATA #REQUIRED id3 CDATA #REQUIRED id4 CDATA #REQUIRED GAB1 CDATA #REQUIRED GAB2 CDATA #REQUIRED>
  <!ELEMENT SynapsesClassification (class*)>
  <!ELEMENT class (#PCDATA)>
  <!ATTLIST class id CDATA #REQUIRED gsyn CDATA #REQUIRED gsynVar CDATA #REQUIRED nsyn CDATA #REQUIRED nsynVar CDATA #REQUIRED dtc CDATA #REQUIRED dtcVar CDATA #REQUIRED u CDATA #REQUIRED uVar CDATA #REQUIRED d CDATA #REQUIRED dVar CDATA #REQUIRED f CDATA #REQUIRED fVar CDATA #REQUIRED ase CDATA #REQUIRED>
  <!ELEMENT ConnectionRules (class*)>  
  <!ELEMENT TouchRules (class*)>
  <!ENTITY connectivityRecipe SYSTEM "builderConnectivityRecipeAllPathways.xml">
]>


<!-- @version: -->

<blueColumn>
<!-- use following line to modify inter-bouton interval algorithm paramters; defaults are min=3, max=7, gap=5
        <InterBoutonInterval minDistance="5.0" maxDistance="9.0" regionGap="5.0"/> 
-->
    <InterBoutonInterval minDistance="5.0" maxDistance="7.0" regionGap="5.0"/> 
    <!-- BrunoMagalhaes, BLBLD-42: Inh and Excitatory filtering distances. defaultSynapsesDistances
         are applied when fromSclass/toSclass/fromMtype rules are not provided
         (if InitialBoutonDistance XML tree not provided, inhibitorySynapsesDistance = 5.0 and excitatorySynapsesDistance = 25.0
         will be used (hard-coded on Functionalizer)-->
    <InitialBoutonDistance defaultInhSynapsesDistance="5.0" defaultExcSynapsesDistance="25.0" />

	<column id="hexagon">
	        <latticeVector id="a1" x="230.92" z="0.0" />
                <latticeVector id="a2" x="-115.46" z="199.98" />
		<layer id="1" thickness="164.94915873" />
		<layer id="2" thickness="148.87602025" />
		<layer id="3" thickness="352.92508322" />
		<layer id="4" thickness="189.57183895" />
		<layer id="5" thickness="525.05585701" />
		<layer id="6" thickness="700.37845971" />
	</column>

	<NeuronTypes totalNeurons="31346" miniColumns="310" IntExtendedMinicolumnRadious="23">
		<Layer id="1" percentage="1.037315">

		  <StructuralType id="L1_DAC" percentage="16.9811320755" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-35">
		    <ElectroType id="bNAC" percentage="33.33"/>
		    <ElectroType id="cNAC" percentage="66.67"/>
		  </StructuralType>
		  <StructuralType id="L1_NGC-DA" percentage="20.7547169811" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-15">
		    <ElectroType id="bNAC" percentage="10.00"/>
		    <ElectroType id="cNAC" percentage="70.00"/>
		    <ElectroType id="cSTUT" percentage="10.00"/>
		    <ElectroType id="cACint" percentage="10.00"/>
		  </StructuralType>
		  <StructuralType id="L1_NGC-SA" percentage="16.3522012579" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
		    <ElectroType id="cNAC" percentage="100.00"/>
		  </StructuralType>
		  <StructuralType id="L1_HAC" percentage="25.786163522" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-26">
		    <ElectroType id="bNAC" percentage="20.00"/>
		    <ElectroType id="cIR" percentage="10.00"/>
		    <ElectroType id="cNAC" percentage="70.00"/>
		  </StructuralType>
		  <StructuralType id="L1_LAC" percentage="8.17610062893" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-46">
		    <ElectroType id="cNAC" percentage="100.00"/>
		  </StructuralType>
		  <StructuralType id="L1_SAC" percentage="11.9496855346" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-27">
		    <ElectroType id="bNAC" percentage="33.33"/>
		    <ElectroType id="cNAC" percentage="50.00"/>
		    <ElectroType id="cACint" percentage="16.67"/>
		  </StructuralType>

<!-- We are leaving CRC cells (1/94) out of the recipe for now as we have no usable reconstructions in MorphologyTracker.  The other cell percentages were recalculated based on 93 total cells.

So, for the recipe, after I exclude the 1 CRC cell, the 2 excitatory cells, and the 16 unclassified cells, I end up with a total of 93 cells and the following percentages:

17/93 = 18.3% NGFC1
16/93 = 17.2% NGFC2
14/93 = 15.1% sLAC
11/93 = 11.8% dLAC
16/93 = 17.2% LSC_DAC
19/93 = 20.4% LSC

			<StructuralType id="CRC" percentage="1.21" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
				<ElectroType id="cACint" percentage="50" />
				<ElectroType id="cNAC" percentage="50" />
			</StructuralType>
-->
		</Layer>
		<Layer id="2" percentage="10.832282">
			<StructuralType id="L2_TPC:A" percentage="8.97435897436" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L2_TPC:B" percentage="56.8376068376" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L2_IPC" percentage="5.98290598291" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>



			<StructuralType id="L23_MC" percentage="4.0293040293" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-120">
			  <ElectroType id="bAC" percentage="2.44"/>
			  <ElectroType id="bNAC" percentage="2.44"/>
			  <ElectroType id="cACint" percentage="82.92"/>
			  <ElectroType id="cNAC" percentage="9.76"/>
			  <ElectroType id="dNAC" percentage="2.44"/>
			</StructuralType>
			<StructuralType id="L23_BTC" percentage="0.895400895399" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-15">
			  <ElectroType id="bAC" percentage="13.89"/>
			  <ElectroType id="bIR" percentage="5.56"/>
			  <ElectroType id="bNAC" percentage="22.22"/>
			  <ElectroType id="cACint" percentage="41.67"/>
			  <ElectroType id="cNAC" percentage="16.67"/>
			</StructuralType>
			<StructuralType id="L23_DBC" percentage="1.7908017908" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="5.88"/>
			  <ElectroType id="bIR" percentage="17.65"/>
			  <ElectroType id="bNAC" percentage="41.18"/>
			  <ElectroType id="cACint" percentage="35.29"/>
			</StructuralType>
			<StructuralType id="L23_BP" percentage="0.4477004477" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="7.14"/>
			  <ElectroType id="bIR" percentage="14.29"/>
			  <ElectroType id="bNAC" percentage="28.57"/>
			  <ElectroType id="cACint" percentage="28.57"/>
			  <ElectroType id="cNAC" percentage="14.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L23_NGC" percentage="2.2385022385" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bNAC" percentage="7.14"/>
			  <ElectroType id="cNAC" percentage="78.58"/>
			  <ElectroType id="cSTUT" percentage="7.14"/>
			  <ElectroType id="cACint" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L23_LBC" percentage="6.2678062678" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="7.46"/>
			  <ElectroType id="bNAC" percentage="5.97"/>
			  <ElectroType id="cACint" percentage="23.88"/>
			  <ElectroType id="cNAC" percentage="16.42"/>
			  <ElectroType id="cSTUT" percentage="4.48"/>
			  <ElectroType id="dNAC" percentage="41.79"/>
			</StructuralType>
			<StructuralType id="L23_NBC" percentage="3.5816035816" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="4.62"/>
			  <ElectroType id="bNAC" percentage="1.54"/>
			  <ElectroType id="cACint" percentage="24.62"/>
			  <ElectroType id="cIR" percentage="1.54"/>
			  <ElectroType id="cNAC" percentage="30.77"/>
			  <ElectroType id="dNAC" percentage="36.92"/>
			</StructuralType>
			<StructuralType id="L23_SBC" percentage="2.2385022385" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bNAC" percentage="35.71"/>
			  <ElectroType id="cACint" percentage="35.71"/>
			  <ElectroType id="dNAC" percentage="28.57"/>
			</StructuralType>
			<StructuralType id="L23_CHC" percentage="6.7155067155" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5" maxHeightRestriction="-15">
			  <ElectroType id="cACint" percentage="37.50"/>
			  <ElectroType id="cNAC" percentage="37.50"/>
			  <ElectroType id="dNAC" percentage="25.00"/>
			</StructuralType>


		</Layer>
		<Layer id="3" percentage="13.075331">
			<StructuralType id="L3_TPC:A" percentage="66.049382716" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L3_TPC:B" percentage="18.8712522046" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L23_MC" percentage="6.0824329732" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="2.44"/>
			  <ElectroType id="bNAC" percentage="2.44"/>
			  <ElectroType id="cACint" percentage="82.92"/>
			  <ElectroType id="cNAC" percentage="9.76"/>
			  <ElectroType id="dNAC" percentage="2.44"/>
			</StructuralType>
			<StructuralType id="L23_BTC" percentage="0.126717353608" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="13.89"/>
			  <ElectroType id="bIR" percentage="5.56"/>
			  <ElectroType id="bNAC" percentage="22.22"/>
			  <ElectroType id="cACint" percentage="41.67"/>
			  <ElectroType id="cNAC" percentage="16.67"/>
			</StructuralType>
			<StructuralType id="L23_DBC" percentage="1.5206082433" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="5.88"/>
			  <ElectroType id="bIR" percentage="17.65"/>
			  <ElectroType id="bNAC" percentage="41.18"/>
			  <ElectroType id="cACint" percentage="35.29"/>
			</StructuralType>
			<StructuralType id="L23_BP" percentage="0.126717353608" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="7.14"/>
			  <ElectroType id="bIR" percentage="14.29"/>
			  <ElectroType id="bNAC" percentage="28.57"/>
			  <ElectroType id="cACint" percentage="28.57"/>
			  <ElectroType id="cNAC" percentage="14.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L23_NGC" percentage="0.253434707217" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bNAC" percentage="7.14"/>
			  <ElectroType id="cNAC" percentage="78.58"/>
			  <ElectroType id="cSTUT" percentage="7.14"/>
			  <ElectroType id="cACint" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L23_LBC" percentage="3.67480325464" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="7.46"/>
			  <ElectroType id="bNAC" percentage="5.97"/>
			  <ElectroType id="cACint" percentage="23.88"/>
			  <ElectroType id="cNAC" percentage="16.42"/>
			  <ElectroType id="cSTUT" percentage="4.48"/>
			  <ElectroType id="dNAC" percentage="41.79"/>
			</StructuralType>
			<StructuralType id="L23_NBC" percentage="2.66106442578" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="4.62"/>
			  <ElectroType id="bNAC" percentage="1.54"/>
			  <ElectroType id="cACint" percentage="24.62"/>
			  <ElectroType id="cIR" percentage="1.54"/>
			  <ElectroType id="cNAC" percentage="30.77"/>
			  <ElectroType id="dNAC" percentage="36.92"/>
			</StructuralType>
			<StructuralType id="L23_SBC" percentage="0.380152060825" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bNAC" percentage="35.71"/>
			  <ElectroType id="cACint" percentage="35.71"/>
			  <ElectroType id="dNAC" percentage="28.57"/>
			</StructuralType>
			<StructuralType id="L23_CHC" percentage="0.253434707217" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="37.50"/>
			  <ElectroType id="cNAC" percentage="37.50"/>
			  <ElectroType id="dNAC" percentage="25.00"/>
			</StructuralType>
		</Layer>
		<Layer id="4" percentage="14.857382">
			<StructuralType id="L4_TPC" percentage="58.1188065489" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>
			<StructuralType id="L4_UPC" percentage="24.1733089186" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>
			<StructuralType id="L4_SSC" percentage="8.22921154675" sigma="20" exclusionRadius="6.0" mClass="INT" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L4_MC" percentage="2.33082122601" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="8.82"/>
			  <ElectroType id="bNAC" percentage="2.94"/>
			  <ElectroType id="cACint" percentage="70.59"/>
			  <ElectroType id="cNAC" percentage="14.71"/>
			  <ElectroType id="dNAC" percentage="2.94"/>
			</StructuralType>
			<StructuralType id="L4_BTC" percentage="0.466164245202" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="7.69"/>
			  <ElectroType id="bIR" percentage="7.69"/>
			  <ElectroType id="bSTUT" percentage="7.69"/>
			  <ElectroType id="cACint" percentage="53.86"/>
			  <ElectroType id="cNAC" percentage="15.38"/>
			  <ElectroType id="dNAC" percentage="7.69"/>
			</StructuralType>
			<StructuralType id="L4_DBC" percentage="0.725144381425" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="9.09"/>
			  <ElectroType id="bIR" percentage="36.36"/>
			  <ElectroType id="bNAC" percentage="9.09"/>
			  <ElectroType id="bSTUT" percentage="9.09"/>
			  <ElectroType id="cACint" percentage="9.09"/>
			  <ElectroType id="cIR" percentage="18.18"/>
			  <ElectroType id="cNAC" percentage="9.09"/>
			</StructuralType>
			<StructuralType id="L4_BP" percentage="0.103592054489" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="7.14"/>
			  <ElectroType id="bIR" percentage="14.29"/>
			  <ElectroType id="bNAC" percentage="28.57"/>
			  <ElectroType id="cACint" percentage="28.57"/>
			  <ElectroType id="cNAC" percentage="14.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L4_NGC" percentage="0.0517960272447" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bNAC" percentage="7.14"/>
			  <ElectroType id="cNAC" percentage="78.58"/>
			  <ElectroType id="cSTUT" percentage="7.14"/>
			  <ElectroType id="cACint" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L4_LBC" percentage="2.4344132805" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="17.86"/>
			  <ElectroType id="cNAC" percentage="10.71"/>
			  <ElectroType id="cSTUT" percentage="25.00"/>
			  <ElectroType id="dNAC" percentage="39.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L4_NBC" percentage="2.07184108979" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="9.52"/>
			  <ElectroType id="cIR" percentage="4.76"/>
			  <ElectroType id="cNAC" percentage="47.62"/>
			  <ElectroType id="dNAC" percentage="38.10"/>
			</StructuralType>
			<StructuralType id="L4_SBC" percentage="1.19130862663" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bNAC" percentage="35.71"/>
			  <ElectroType id="cACint" percentage="35.71"/>
			  <ElectroType id="dNAC" percentage="28.57"/>
			</StructuralType>
			<StructuralType id="L4_CHC" percentage="0.103592054489" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="37.50"/>
			  <ElectroType id="cNAC" percentage="37.50"/>
			  <ElectroType id="dNAC" percentage="25.00"/>
			</StructuralType>

		</Layer>
		<Layer id="5" percentage="19.485231">
			<StructuralType id="L5_TPC:A" percentage="39.6061105299" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L5_TPC:B" percentage="32.3044253484" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L5_TPC:C" percentage="5.53157968294" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L5_UPC" percentage="5.70395185437" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>


			<StructuralType id="L5_MC" percentage="6.01926163724" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="37.04"/>
			  <ElectroType id="bIR" percentage="11.11"/>
			  <ElectroType id="bSTUT" percentage="3.70"/>
			  <ElectroType id="cACint" percentage="37.04"/>
			  <ElectroType id="cNAC" percentage="3.70"/>
			  <ElectroType id="cSTUT" percentage="3.70"/>
			  <ElectroType id="dNAC" percentage="3.70"/>
			</StructuralType>
			<StructuralType id="L5_BTC" percentage="1.28984177941" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="16.67"/>
			  <ElectroType id="cACint" percentage="66.66"/>
			  <ElectroType id="cNAC" percentage="16.67"/>
			</StructuralType>
			<StructuralType id="L5_DBC" percentage="1.37583123137" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="9.09"/>
			  <ElectroType id="bIR" percentage="36.36"/>
			  <ElectroType id="bNAC" percentage="9.09"/>
			  <ElectroType id="bSTUT" percentage="9.09"/>
			  <ElectroType id="cACint" percentage="9.09"/>
			  <ElectroType id="cIR" percentage="18.18"/>
			  <ElectroType id="cNAC" percentage="9.09"/>
			</StructuralType>
			<StructuralType id="L5_BP" percentage="0.601926163724" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="7.14"/>
			  <ElectroType id="bIR" percentage="14.29"/>
			  <ElectroType id="bNAC" percentage="28.57"/>
			  <ElectroType id="cACint" percentage="28.57"/>
			  <ElectroType id="cNAC" percentage="14.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L5_NGC" percentage="0.171978903921" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bNAC" percentage="7.14"/>
			  <ElectroType id="cNAC" percentage="78.58"/>
			  <ElectroType id="cSTUT" percentage="7.14"/>
			  <ElectroType id="cACint" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L5_LBC" percentage="3.35358862646" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="5.88"/>
			  <ElectroType id="cACint" percentage="11.76"/>
			  <ElectroType id="cIR" percentage="5.88"/>
			  <ElectroType id="cNAC" percentage="17.65"/>
			  <ElectroType id="cSTUT" percentage="17.65"/>
			  <ElectroType id="dNAC" percentage="17.65"/>
			  <ElectroType id="dSTUT" percentage="23.53"/>
			</StructuralType>
			<StructuralType id="L5_NBC" percentage="3.2675991745" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="6.67"/>
			  <ElectroType id="bIR" percentage="6.67"/>
			  <ElectroType id="bSTUT" percentage="13.33"/>
			  <ElectroType id="cACint" percentage="20.00"/>
			  <ElectroType id="cIR" percentage="6.67"/>
			  <ElectroType id="cNAC" percentage="20.00"/>
			  <ElectroType id="cSTUT" percentage="20.00"/>
			  <ElectroType id="dSTUT" percentage="6.67"/>
			</StructuralType>
			<StructuralType id="L5_SBC" percentage="0.515936711764" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bNAC" percentage="35.71"/>
			  <ElectroType id="cACint" percentage="35.71"/>
			  <ElectroType id="dNAC" percentage="28.57"/>
			</StructuralType>
			<StructuralType id="L5_CHC" percentage="0.257968355882" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="37.50"/>
			  <ElectroType id="cNAC" percentage="37.50"/>
			  <ElectroType id="dNAC" percentage="25.00"/>
			</StructuralType>

		</Layer>
		<Layer id="6" percentage="40.712459">
<!--			<StructuralType id="L6_HPC" percentage="0.0" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100" />
			</StructuralType>
-->
			<StructuralType id="L6_TPC:A" percentage="17.6264746519" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L6_TPC:C" percentage="11.7509831013" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>

			<StructuralType id="L6_UPC" percentage="9.32617706452" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>
			<StructuralType id="L6_IPC" percentage="20.5175895419" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/>
			</StructuralType>
			<StructuralType id="L6_BPC" percentage="16.3208098629" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/> <!-- currently L6FFPC is used -->
			</StructuralType>

			<StructuralType id="L6_HPC" percentage="14.9218833032" sigma="20" exclusionRadius="6.0" mClass="PYR" sClass="EXC" spineLength="2.5">
				<ElectroType id="cADpyr" percentage="100"/> 
			</StructuralType>


			<StructuralType id="L6_MC" percentage="2.36364437395" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="12.00"/>
			  <ElectroType id="bIR" percentage="44.00"/>
			  <ElectroType id="bNAC" percentage="4.0"/>
			  <ElectroType id="bSTUT" percentage="4.0"/>
			  <ElectroType id="cACint" percentage="28.00"/>
			  <ElectroType id="cIR" percentage="4.00"/>
			  <ElectroType id="cNAC" percentage="4.00"/>
			</StructuralType>
			<StructuralType id="L6_BTC" percentage="0.407524892061" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="16.67"/>
			  <ElectroType id="cACint" percentage="66.66"/>
			  <ElectroType id="cNAC" percentage="16.67"/>
			</StructuralType>
			<StructuralType id="L6_DBC" percentage="0.163009956824" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="9.09"/>
			  <ElectroType id="bIR" percentage="36.36"/>
			  <ElectroType id="bNAC" percentage="9.09"/>
			  <ElectroType id="bSTUT" percentage="9.09"/>
			  <ElectroType id="cACint" percentage="9.09"/>
			  <ElectroType id="cIR" percentage="18.18"/>
			  <ElectroType id="cNAC" percentage="9.09"/>
			</StructuralType>
			<StructuralType id="L6_BP" percentage="0.407524892061" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bAC" percentage="7.14"/>
			  <ElectroType id="bIR" percentage="14.29"/>
			  <ElectroType id="bNAC" percentage="28.57"/>
			  <ElectroType id="cACint" percentage="28.57"/>
			  <ElectroType id="cNAC" percentage="14.29"/>
			  <ElectroType id="dSTUT" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L6_NGC" percentage="0.0815049784122" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="0.5">
			  <ElectroType id="bNAC" percentage="7.14"/>
			  <ElectroType id="cNAC" percentage="78.58"/>
			  <ElectroType id="cSTUT" percentage="7.14"/>
			  <ElectroType id="cACint" percentage="7.14"/>
			</StructuralType>
			<StructuralType id="L6_LBC" percentage="4.23825887743" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="18.18"/>
			  <ElectroType id="bIR" percentage="27.27"/>
			  <ElectroType id="bNAC" percentage="9.09"/>
			  <ElectroType id="bSTUT" percentage="27.27"/>
			  <ElectroType id="cNAC" percentage="9.09"/>
			  <ElectroType id="cSTUT" percentage="9.09"/>
			</StructuralType>
			<StructuralType id="L6_NBC" percentage="1.38558463301" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bAC" percentage="6.67"/>
			  <ElectroType id="bIR" percentage="6.67"/>
			  <ElectroType id="bSTUT" percentage="13.33"/>
			  <ElectroType id="cACint" percentage="20.00"/>
			  <ElectroType id="cIR" percentage="6.67"/>
			  <ElectroType id="cNAC" percentage="20.00"/>
			  <ElectroType id="cSTUT" percentage="20.00"/>
			  <ElectroType id="dSTUT" percentage="6.67"/>
			</StructuralType>
			<StructuralType id="L6_SBC" percentage="0.407524892061" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="bNAC" percentage="35.71"/>
			  <ElectroType id="cACint" percentage="35.71"/>
			  <ElectroType id="dNAC" percentage="28.57"/>
			</StructuralType>
			<StructuralType id="L6_CHC" percentage="0.0815049784122" sigma="25" exclusionRadius="6.0" mClass="INT" sClass="INH" spineLength="2.5">
			  <ElectroType id="cACint" percentage="37.50"/>
			  <ElectroType id="cNAC" percentage="37.50"/>
			  <ElectroType id="dNAC" percentage="25.00"/>
			</StructuralType>
		</Layer>
	</NeuronTypes>
	
<!--	<Seeds recipeSeed="837632" columnSeed="2906729" synapseSeed="4236279"/>
-->

	<SynapsesProperties neuralTransmitterReleaseDelay="0.1" axonalConductionVelocity="300.0">
		<synapse fromSClass="EXC" toSClass="EXC" type="E2" />
		<synapse fromSClass="INH" toSClass="INH" type="I2" />

		<synapse fromSClass="EXC" toSClass="INH" type="E2_INH" />
		<synapse fromSClass="INH" toSClass="EXC" type="I2" />

	
<!-- new synapse rules to assign specific USE value for select pyr-pyr pathways from literature. SR -->
                <synapse fromMType="L3_TPC:*" toMType="L3_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L2_TPC:*" toMType="L3_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L2_IPC" toMType="L3_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L2_TPC:*" toMType="L2_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L2_TPC:*" toMType="L2_IPC" type="E2_L3PC" />
                <synapse fromMType="L2_IPC" toMType="L2_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L2_IPC" toMType="L2_IPC" type="E2_L3PC" />
                <synapse fromMType="L3_TPC:*" toMType="L2_TPC:*" type="E2_L3PC" />
                <synapse fromMType="L3_TPC:*" toMType="L2_IPC" type="E2_L3PC" />

                <synapse fromMType="L4_*PC" toMType="L4_*PC" type="E2_L4PC" />
                <synapse fromMType="L4_*PC" toMType="L4_SSC" type="E2_L4PC" />
                <synapse fromMType="L4_SSC" toMType="L4_*PC" type="E2_L4PC" />
                <synapse fromMType="L4_SSC" toMType="L4_SSC" type="E2_L4PC" />

                <synapse fromMType="L4_SSC" toMType="L2_*PC" type="E2_L4SS" />
                <synapse fromMType="L4_SSC" toMType="L3_TPC:*" type="E2_L4SS" />

                <synapse fromMType="L5_TPC:C" toMType="L5_TPC:*" type="E2_L5STPC" />